### ISSUE TITLE
Python packages for conda env

### ISSUE THREAD

**Issue by emiliom** [ioos/BioData-Training-Workshop#4]
@ocefpaf @bbest @jbosch-noaa Last week Don (@lsetiawan) started putting together a Docker file for the AWS cloud instance that'll host JupyterHub. He created a basic conda environment file for Python. It's [here](), but I'm pasting the listing of packages below, for your convenience.

If there are other Python packages you think we should include, please chime in via this issue. Remember that many of the packages below have a lot of dependencies that will be brought in by default, such as numpy, pandas, matplotlib, netcdf4, etc.

For example: 
- @ocefpaf, is your [erddapy](https://github.com/pyoceans/erddapy) package mature enough to be included?
- Is there such a thing as a Python Darwin Core reader / writer, or API to the biological taxonomy resources, that we should include?

@bbest feel free to open a similar github issue for R if you'd like, and ping Abby on that issue.

Here's the conda env file:

```yaml
name: iooswkshp
channels:
- conda-forge
dependencies:
- python=3.6
- requests
- scipy
- xarray
- folium
- geopandas
- gdal=2.2
# Jupyter notebook
- ipykernel
- jupyter
- nb_conda_kernels
```
